# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Package publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    if: startsWith(github.event.head_commit.message, 'build:')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun.js setup
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint check
        run: bun run lint

      - name: Run tests
        run: bun run test

      - name: Build sources
        run: bun run build

      - name: Publish package to NPM
        run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
