name: PR check

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  pr_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Bun.js setup
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint check
        run: bun run lint

      - name: TypeScript Check
        run: bun run ts-check
